"""Regenerate the sequencing map inside a tracking issue's body.

The tracker's *truth* is GitHub's own graph: native sub-issues say what the work is,
and native issue dependencies say what blocks what. Neither can drift, because GitHub
computes both. This script renders that graph into a readable block and splices it into
the tracking issue between two HTML comment markers. It is a **view**, never a source —
if it stops running, the graph is still correct and `gh` still answers correctly.

That distinction is the whole design. A hand-maintained checkbox list went wrong 8 times
out of 19 in two days; the failure mode of *this* file is different and milder, because
the block it writes carries a generation stamp. A stale stamp is visible on the face of
the issue, where a stale checkbox is not.

Run it with GH_TOKEN set and the repo/issue passed in the environment.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from datetime import datetime, timezone

START = "<!-- SEQUENCING:START -->"
END = "<!-- SEQUENCING:END -->"

# Keep node labels short — mermaid renders the whole graph on one line otherwise. The
# issue number stays in the label so a reader can navigate without the edge list.
LABEL_MAX = 34


def gh_api(path: str, *, paginate: bool = False) -> object:
    """Return parsed JSON from the GitHub API, or raise with the body attached.

    `encoding` is pinned rather than left to `text=True`, which resolves to the locale
    codec — cp1252 on a Windows checkout, which cannot decode the German cues and box
    characters these issues are full of. The runner is UTF-8 so CI would never have
    caught it; a maintainer running this by hand would hit it immediately. Same class
    as the runtime UTF-8 pin in #64/#68.

    `paginate` is required on every *list* endpoint. GitHub's default page is 30 and a
    truncated page is not an error — the caller just sees a shorter list and renders a
    confidently wrong map. `gh --paginate` merges the pages of a top-level JSON array
    into one array, so the result stays a single parseable document.
    """
    args = ["gh", "api", path] + (["--paginate"] if paginate else [])
    result = subprocess.run(
        args,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"gh api {path} failed: {(result.stderr or '').strip()}")
    return json.loads(result.stdout)


def short(title: str) -> str:
    """Trim a title to something a mermaid node can hold, and strip quotes it cannot."""
    cleaned = title.replace('"', "'").strip()
    if len(cleaned) <= LABEL_MAX:
        return cleaned
    return cleaned[: LABEL_MAX - 1].rstrip() + "…"


def main() -> int:
    repo = os.environ["TRACKER_REPO"]
    issue = os.environ["TRACKER_ISSUE"]
    run_url = os.environ.get("RUN_URL", "")

    children = gh_api(f"repos/{repo}/issues/{issue}/sub_issues?per_page=100", paginate=True)
    if not isinstance(children, list):
        raise RuntimeError("sub_issues did not return a list")

    open_children = [c for c in children if c["state"] == "open"]
    closed_count = len(children) - len(open_children)

    # blocked_by is fetched per issue rather than read off the listing: the summary on a
    # listing response is not guaranteed to carry the *identities* of the blockers, and
    # the table below names them. Open blockers only — a closed blocker is not a block.
    blockers: dict[int, list[dict]] = {}
    for child in open_children:
        number = child["number"]
        edges = gh_api(
            f"repos/{repo}/issues/{number}/dependencies/blocked_by?per_page=100",
            paginate=True,
        )
        blockers[number] = [b for b in edges if b["state"] == "open"]

    blocked = {n: b for n, b in blockers.items() if b}
    ready = [c for c in open_children if not blockers[c["number"]]]

    lines: list[str] = [START, "### Sequencing map", ""]
    lines += [
        "> ⚠️ **Generated block — do not hand-edit.** Regenerated by "
        "`.github/workflows/tracker-map.yml` from the live sub-issue and dependency "
        "graph. **If the stamp below is more than ~24h old the workflow is not "
        "running**, and this section is stale even though the rest of the tracker is "
        "not. The graph itself is still correct — query it directly with `gh`.",
        ">",
        f"> Last generated: `{datetime.now(timezone.utc):%Y-%m-%d %H:%MZ}`"
        + (f" · [run]({run_url})" if run_url else ""),
        "",
    ]

    titles = {c["number"]: c["title"] for c in open_children}

    lines += ["```mermaid", "graph LR"]
    if ready:
        lines.append('  subgraph ready["Ready — no open blockers"]')
        for child in sorted(ready, key=lambda c: c["number"]):
            n = child["number"]
            lines.append(f'    I{n}["#{n} · {short(child["title"])}"]')
        lines.append("  end")
    # Declare every blocked node once before drawing edges. Repeating the label on each
    # edge renders the same (mermaid takes the last), but a node with two blockers then
    # appears twice in the source, which reads like a duplicate rather than a join.
    for number in sorted(blocked):
        lines.append(f'  I{number}["#{number} · {short(titles[number])}"]')
    for number, edges in sorted(blocked.items()):
        for edge in sorted(edges, key=lambda e: e["number"]):
            lines.append(f'  I{edge["number"]} --> I{number}')
    lines += ["```", ""]

    lines.append(
        f"**Open: {len(open_children)} · Ready: {len(ready)} · "
        f"Blocked: {len(blocked)} · Closed: {closed_count}**"
    )

    if blocked:
        lines += ["", "| Blocked | Waiting on |", "|---|---|"]
        for number, edges in sorted(blocked.items()):
            waiting = ", ".join(f"#{e['number']}" for e in sorted(edges, key=lambda e: e["number"]))
            lines.append(f"| #{number} · {short(titles[number])} | {waiting} |")

    lines.append(END)
    rendered = "\n".join(lines)

    body = gh_api(f"repos/{repo}/issues/{issue}")["body"] or ""
    starts, ends = body.count(START), body.count(END)
    # Membership is not enough, because the splice below keeps everything *before* START
    # and everything *after* END. If END precedes START, `rest.partition(END)` finds no
    # END and yields an empty tail — the whole issue body after START is deleted and the
    # run still prints success. Two pairs are milder but leave a stale second map lying.
    # Both are unrecoverable-by-the-script states, so require exactly one ordered pair
    # and refuse: a wrong tracker body is the failure this whole file exists to prevent.
    if starts != 1 or ends != 1 or body.index(START) > body.index(END):
        print(
            f"::error::issue #{issue} body must contain exactly one "
            f"{START} … {END} pair, in that order "
            f"(found {starts} start / {ends} end marker(s))"
        )
        return 1

    head, _, rest = body.partition(START)
    _, _, tail = rest.partition(END)
    updated = f"{head}{rendered}{tail}"

    if updated == body:
        print("Sequencing map unchanged — nothing to write.")
        return 0

    # The stamp changes every run, so the body almost always differs. That is deliberate:
    # a stamp that only refreshes when the graph moves cannot be used to tell a live
    # workflow from a dead one, which is the property the block's own warning relies on.
    # Say which kind of write this was, so the run log stays readable.
    def without_stamp(text: str) -> str:
        return "\n".join(
            line for line in text.splitlines() if not line.startswith("> Last generated:")
        )

    kind = "graph changed" if without_stamp(updated) != without_stamp(body) else "stamp refreshed"

    subprocess.run(
        ["gh", "api", "--method", "PATCH", f"repos/{repo}/issues/{issue}", "-F", "body=@-"],
        input=updated,
        text=True,
        encoding="utf-8",
        check=True,
        capture_output=True,
    )
    print(
        f"Sequencing map written ({kind}): "
        f"{len(open_children)} open, {len(ready)} ready, {len(blocked)} blocked."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
